import { Metadata } from 'next'



export const metadata: Metadata = {
  title: {
    default:"next - shyam",
    template:"%s | SHYAM"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     

      <body>
      <header style={{
        backgroundColor: "lightblue",
        padding: "1rem",
      }}>
       
      </header>
        {children}

        <footer style={{
        backgroundColor: "lightsteelblue",
        padding: "1rem",
      }}>
          <p>HI 2023 My Company. All rights reserved.</p>
        </footer>
      </body>
    </html>
  )
}
