export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     

      <body>
      <header style={{
        backgroundColor: "lightblue",
        padding: "1rem",
      }}>
        <h1>{metadata.title}</h1>
       
      </header>
        {children}

        <footer style={{
        backgroundColor: "lightpink",
        padding: "1rem",
      }}>
          <p>HI 2023 My Company. All rights reserved.</p>
        </footer>
      </body>
    </html>
  )
}
